version: '3.1'

networks:
   wlsnet:

services:

  wlsadmin:
    image: pvdbleek/wls-app
    networks:
      wlsnet:
    ports:
      - 7001:7001

  managedserver:
    image: pvdbleek/wls-app
    command: createServer.sh
    networks:
      wlsnet:
    ports:
     - 7002:7002
    depends_on:
     - wlsadmin
