version: '3.1'

networks:
   oranet:
     external: true

services:

  wlsadmin:
    image: pvdbleek/wls-app:latest
    networks:
      oranet:
    ports:
      - 7001:7001

  managedserver:
    image: pvdbleek/wls-app:latest
    command: createServer.sh
    networks:
      oranet:
    ports:
     - 7002:7002
    depends_on:
     - wlsadmin


